apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myacr351f520047da48a7.azurecr.io/myapp:v1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod"
        ports:
        - containerPort: 8081
