@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.github.daveb8772.cms.cmsrestservice.controller.Models.EntityModels.ChargingPoint",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1245635613 { 
   	label=github
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1638032187 { 
   	label=daveb8772
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AuthorizationResponse10890254[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AuthorizationResponse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   authorization: AuthorizationDTO [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   responseStatus: ResponseStatus [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChargingPoint1462292524[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChargingPoint</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   availabilityStatus: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   chargingPointId: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   chargingProfiles: List&lt;ChargingProfile&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commandRequests: List&lt;CommandRequest&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorCapabilities: ConnectorCapabilities [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorPower: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorStatus: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectors: Set&lt;Connector&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   currentUtilization: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lastUpdate: ZonedDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   maxChargingPower: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   status: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tariffIds: List&lt;String&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addChargingProfile(chargingProfile: ChargingProfile)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChargingPointDTO2014407926[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChargingPointDTO</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   availabilityStatus: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   chargingPointId: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   chargingProfiles: List&lt;ChargingProfileDTO&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commandRequests: List&lt;CommandRequestDTO&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connector: Set&lt;ConnectorDTO&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorCapabilities: ConnectorCapabilitiesDTO [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorPower: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorStatus: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   currentUtilization: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lastUpdate: ZonedDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   maxChargingPower: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   status: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tariffIds: List&lt;String&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ fromEntity(chargingPoint: ChargingPoint): ChargingPointDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChargingPointDataResponse10890254[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChargingPointDataResponse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   chargingPoints: List&lt;ChargingPointDTO&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   responseStatus: ResponseStatus [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChargingProfile1462292524[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChargingProfile</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   chargingPower: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   validFrom: LocalDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   validTo: LocalDateTime [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChargingSessionDataResponse10890254[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChargingSessionDataResponse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   chargingSessions: List&lt;ChargingSessionDTO&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   responseStatus: ResponseStatus [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommandRequest1462292524[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommandRequest</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   chargingPoint: ChargingPoint [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commandParameter: String [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commandType: CommandType [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timestamp: LocalDateTime [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommandRequestDTO2014407926[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommandRequestDTO</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   chargingPoint: ChargingPoint [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commandParameter: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commandType: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timestamp: LocalDateTime [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ fromEntity(commandRequest: CommandRequest): CommandRequestDTO</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommandResponse10890254[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommandResponse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   responseStatus: ResponseStatus [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   result: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Connector1462292524[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Connector</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   chargingMode: ChargingModeValue [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   chargingPoint: ChargingPoint [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorId: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   connectorType: ConnectorType [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   currentChargingSessionId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   isOccupied: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   power: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   status: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ConnectorCapabilities1462292524[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ConnectorCapabilities</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bidirectionalCharging: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   chargeMode: ChargingModeValue [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   communicationProtocol: CommunicationProtocolValue [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dynamicPowerSharing: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   maximumPower: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   plugType: ConnectorType [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

LocationInfo1462292524[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)LocationInfo</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   accessibilityInformation: Accessibility [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   chargingPoints: List&lt;ChargingPoint&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   contactInformation: ContactDetails [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   details: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   locationAddress: Address [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   locationId: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   openingHours: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pointsOfInterest: List&lt;PointOfInterest&gt; [0..*]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SupportedVersionsResponse10890254[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SupportedVersionsResponse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   supportedVersions: List&lt;String&gt; [0..*]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

TariffDataResponse10890254[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)TariffDataResponse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   responseStatus: ResponseStatus [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tariffs: List&lt;TariffDTO&gt; [0..*]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ChargingPoint1462292524 -> ChargingProfile1462292524[label="chargingProfiles
[0..*]"];
ChargingPoint1462292524 -> CommandRequest1462292524[label="commandRequests
[0..*]"];
ChargingPoint1462292524 -> Connector1462292524[label="connectors
[0..*]"];
ChargingPoint1462292524 -> ConnectorCapabilities1462292524[label="connectorCapabilities
[0..1]"];
ChargingPointDTO2014407926 -> CommandRequestDTO2014407926[label="commandRequests
[0..*]"];
ChargingPointDataResponse10890254 -> AuthorizationResponse10890254[arrowhead=none];
ChargingPointDataResponse10890254 -> ChargingPointDTO2014407926[label="chargingPoints
[0..*]"];
ChargingPointDataResponse10890254 -> ChargingSessionDataResponse10890254[arrowhead=none];
ChargingPointDataResponse10890254 -> CommandResponse10890254[arrowhead=none];
ChargingPointDataResponse10890254 -> SupportedVersionsResponse10890254[arrowhead=none];
ChargingPointDataResponse10890254 -> TariffDataResponse10890254[arrowhead=none];
CommandRequest1462292524 -> ChargingPoint1462292524[label="chargingPoint
[0..1]"];
CommandRequestDTO2014407926 -> ChargingPoint1462292524[label="chargingPoint
[0..1]"];
Connector1462292524 -> ChargingPoint1462292524[label="chargingPoint
[0..1]"];
LocationInfo1462292524 -> ChargingPoint1462292524[label="chargingPoints
[0..*]"];
    
}
@enduml